query($where:JSON){
  vehiculoimagens(where: $where ){
  	id
     url_imagen{
        id
        name
        url
      }
      vehiculoanio{
        id
        anio{
          id
          anio_publicado
        }
        vehiculo{
          id
          modelo
          categoria{
            id
            name
          }
        }
    }
  }
}